name: Build

on:
  push:
  workflow_dispatch:

jobs:
  Release-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Release
        run: |
          bash build-release.sh
      - name: Upload Release Build
        uses: actions/upload-artifact@v4
        with:
          name: Release Build
          path: builds/release

